// Generated by Haxe 3.4.0
(function () { "use strict";
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var _$Pipeline_Pipeline_$Impl_$ = {};
_$Pipeline_Pipeline_$Impl_$.iterator = function(this1) {
	return $iterator(this1)();
};
_$Pipeline_Pipeline_$Impl_$.open = function(tar) {
	if(tar == null) {
		throw new Error("tar is null");
	}
	return tar;
};
_$Pipeline_Pipeline_$Impl_$.openFields = function(tar) {
	if(tar == null) {
		throw new Error("tar is null");
	}
	return { iterator : function() {
		var fields = HxOverrides.iter(Reflect.fields(tar));
		var nex = false;
		return { hasNext : function() {
			nex = fields.hasNext();
			return nex;
		}, next : function() {
			if(!nex) {
				throw new Error("no elem");
			}
			var key = fields.next();
			var value = Reflect.field(tar,key);
			return { key : key, value : value};
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.openMap = function(tar) {
	if(tar == null) {
		throw new Error("tar is null");
	}
	return { iterator : function() {
		var keys = tar.keys();
		var nex = false;
		return { hasNext : function() {
			nex = keys.hasNext();
			return nex;
		}, next : function() {
			var key = keys.next();
			var value = tar.get(key);
			return { key : key, value : value};
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.enumerate = function(begin,end) {
	if(begin >= end) {
		throw new Error("invalid range");
	}
	return { iterator : function() {
		var pos = begin;
		return { hasNext : function() {
			return pos < end;
		}, next : function() {
			pos += 1;
			return pos - 1;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.where = function(this1,pred) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(pred == null) {
		throw new Error("pred is null");
	}
	return { iterator : function() {
		var fet = false;
		var nex = null;
		var itr = $iterator(this1)();
		var took = true;
		return { hasNext : function() {
			if(!took) {
				return fet;
			}
			took = false;
			while(true) {
				var tmp;
				fet = itr.hasNext();
				if(fet) {
					nex = itr.next();
					tmp = !pred(nex);
				} else {
					tmp = false;
				}
				if(!tmp) {
					break;
				}
			}
			return fet;
		}, next : function() {
			if(!fet) {
				throw new Error("no next");
			}
			took = true;
			return nex;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.select = function(this1,selector) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(selector == null) {
		throw new Error("selector is null");
	}
	return { iterator : function() {
		var fet = false;
		var nex = null;
		var itr = $iterator(this1)();
		var took = true;
		return { hasNext : function() {
			if(!took) {
				return fet;
			}
			took = false;
			fet = itr.hasNext();
			if(!fet) {
				return false;
			}
			var nex1 = itr.next();
			nex = selector(nex1);
			return true;
		}, next : function() {
			if(!fet) {
				throw new Error("no next");
			}
			took = true;
			return nex;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.join = function(this1,tar,join) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(join == null) {
		throw new Error("join is null");
	}
	return { iterator : function() {
		var fet = false;
		var nex = null;
		var elx = null;
		var itrx = $iterator(this1)();
		var itry = null;
		var first = true;
		var took = true;
		return { hasNext : function() {
			if(!took) {
				return fet;
			}
			took = false;
			if(first || !itry.hasNext()) {
				first = false;
				fet = itrx.hasNext();
				if(!fet) {
					return false;
				}
				elx = itrx.next();
				itry = $iterator(_$Pipeline_Pipeline_$Impl_$)(tar);
			}
			fet = itry.hasNext();
			if(!fet) {
				return false;
			}
			var nex1 = itry.next();
			nex = join(elx,nex1);
			return true;
		}, next : function() {
			if(!fet) {
				throw new Error("no next");
			}
			took = true;
			return nex;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.apply = function(this1,com) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(com == null) {
		throw new Error("com is null");
	}
	return { iterator : function() {
		var itr = $iterator(this1)();
		var nex = null;
		var fet = false;
		var took = true;
		return { hasNext : function() {
			if(!took) {
				return fet;
			}
			took = false;
			fet = itr.hasNext();
			if(!fet) {
				return false;
			}
			nex = itr.next();
			com(nex);
			return true;
		}, next : function() {
			if(!fet) {
				throw new Error("no next");
			}
			took = true;
			return nex;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.explore = function(this1,explorer) {
	if(this1 == null) {
		throw new Error("this is null");
	}
	if(explorer == null) {
		throw new Error("explorer is null");
	}
	return { iterator : function() {
		var stack = [];
		var x = $iterator(this1)();
		while(x.hasNext()) {
			var x1 = x.next();
			stack.push(x1);
		}
		return { hasNext : function() {
			return stack.length > 0;
		}, next : function() {
			if(stack.length <= 0) {
				throw new Error("no elem");
			}
			var ret = stack.pop();
			var child = explorer(ret);
			if(child != null) {
				var x2 = $iterator(child)();
				while(x2.hasNext()) {
					var x3 = x2.next();
					stack.push(x3);
				}
			}
			return ret;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.sort = function(this1,com) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(com == null) {
		throw new Error("com is null");
	}
	return { iterator : function() {
		var ret = [];
		var x = $iterator(this1)();
		while(x.hasNext()) {
			var x1 = x.next();
			ret.push(x1);
		}
		ret.sort(com);
		return HxOverrides.iter(ret);
	}};
};
_$Pipeline_Pipeline_$Impl_$.skip = function(this1,count) {
	if(count < 0) {
		throw new Error("neg count");
	}
	return { iterator : function() {
		var itr = $iterator(this1)();
		var _g1 = 0;
		var _g = count;
		while(_g1 < _g) {
			var i = _g1++;
			if(!itr.hasNext()) {
				break;
			}
			itr.next();
		}
		return itr;
	}};
};
_$Pipeline_Pipeline_$Impl_$.limit = function(this1,count) {
	if(count < 0) {
		throw new Error("neg count");
	}
	return { iterator : function() {
		var itr = $iterator(this1)();
		var cur = 0;
		var nex = false;
		return { hasNext : function() {
			if(itr.hasNext()) {
				nex = cur < count;
			} else {
				nex = false;
			}
			return nex;
		}, next : function() {
			if(!nex) {
				throw new Error("no elem");
			}
			cur += 1;
			return itr.next();
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.foreach = function(this1,com) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(com == null) {
		throw new Error("com is null");
	}
	var x = $iterator(this1)();
	while(x.hasNext()) {
		var x1 = x.next();
		com(x1);
	}
};
_$Pipeline_Pipeline_$Impl_$.aggregate = function(this1,zero,agr,saf) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(agr == null) {
		throw new Error("agr is null");
	}
	var ret = zero;
	var count = 0;
	var x = $iterator(this1)();
	while(x.hasNext()) {
		var x1 = x.next();
		ret = agr(ret,x1);
		++count;
	}
	if(saf != null) {
		return saf(ret,count);
	} else {
		return ret;
	}
};
_$Pipeline_Pipeline_$Impl_$.argmin = function(this1,$eval) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if($eval == null) {
		throw new Error("eval is null");
	}
	var itr = $iterator(this1)();
	if(!itr.hasNext()) {
		throw new Error("no elem");
	}
	var ret = null;
	var val = null;
	while(true) {
		var x = itr.next();
		var y = $eval(x);
		if(val == null || val > y) {
			ret = x;
			val = y;
		}
		if(!itr.hasNext()) {
			break;
		}
	}
	return ret;
};
_$Pipeline_Pipeline_$Impl_$.argmax = function(this1,$eval) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if($eval == null) {
		throw new Error("eval is null");
	}
	var itr = $iterator(this1)();
	if(!itr.hasNext()) {
		throw new Error("no elem");
	}
	var ret = null;
	var val = null;
	while(true) {
		var x = itr.next();
		var y = $eval(x);
		if(val == null || val < y) {
			ret = x;
			val = y;
		}
		if(!itr.hasNext()) {
			break;
		}
	}
	return ret;
};
_$Pipeline_Pipeline_$Impl_$.first = function(this1) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	var itr = $iterator(this1)();
	if(!itr.hasNext()) {
		throw new Error("no first element");
	}
	return itr.next();
};
_$Pipeline_Pipeline_$Impl_$.last = function(this1) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	var itr = $iterator(this1)();
	if(!itr.hasNext()) {
		throw new Error("no elem");
	}
	var ret;
	while(true) {
		ret = itr.next();
		if(!itr.hasNext()) {
			break;
		}
	}
	return ret;
};
_$Pipeline_Pipeline_$Impl_$.count = function(this1) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	var ret = 0;
	var x = $iterator(this1)();
	while(x.hasNext()) {
		var x1 = x.next();
		++ret;
	}
	return ret;
};
_$Pipeline_Pipeline_$Impl_$.any = function(this1,pred) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(pred == null) {
		throw new Error("pred is null");
	}
	var x = $iterator(this1)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(pred(x1)) {
			return true;
		}
	}
	return false;
};
_$Pipeline_Pipeline_$Impl_$.all = function(this1,pred) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(pred == null) {
		throw new Error("pred is null");
	}
	var x = $iterator(this1)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(!pred(x1)) {
			return false;
		}
	}
	return true;
};
_$Pipeline_Pipeline_$Impl_$.toArray = function(this1) {
	if(this1 == null) {
		throw new Error("this is null");
	}
	var ret = [];
	var x = $iterator(this1)();
	while(x.hasNext()) {
		var x1 = x.next();
		ret.push(x1);
	}
	return ret;
};
var Reflect = function() { };
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		return null;
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) {
			a.push(f);
		}
		}
	}
	return a;
};
var Sample1 = function() { };
Sample1.main = function() {
	console.log("#show all entries in obj");
	var pip = _$Pipeline_Pipeline_$Impl_$.openFields(Sample1.obj);
	_$Pipeline_Pipeline_$Impl_$.foreach(pip,function(x) {
		console.log(x);
	});
	console.log("#show all entries in map");
	var mappip = _$Pipeline_Pipeline_$Impl_$.openMap(Sample1.map);
	_$Pipeline_Pipeline_$Impl_$.foreach(mappip,function(x1) {
		console.log(x1);
	});
	console.log("show all entries size in bytes");
	_$Pipeline_Pipeline_$Impl_$.foreach(_$Pipeline_Pipeline_$Impl_$.select(pip,function(x2) {
		return x2.value.length;
	}),function(x3) {
		console.log(x3);
	});
	var gui = { type : "form", children : []};
	var radios = { type : "group", children : []};
	var radio0 = { type : "radio", name : "radio0", children : []};
	var radio1 = { type : "radio", name : "radio1", children : []};
	radios.children.push(radio0);
	radios.children.push(radio1);
	gui.children.push(radios);
	var ok = { type : "button", name : "ok", children : []};
	gui.children.push(ok);
	var cancel = { type : "button", name : "cancel", children : []};
	gui.children.push(cancel);
	console.log("=======gui========");
	console.log("=====radios=======");
	console.log("o radio0");
	console.log("o radio1");
	console.log("==================");
	console.log("[ok] [cancel]");
	console.log("==================");
	console.log("#get all button or radio names from gui data structure");
	_$Pipeline_Pipeline_$Impl_$.foreach(_$Pipeline_Pipeline_$Impl_$.select(_$Pipeline_Pipeline_$Impl_$.where(_$Pipeline_Pipeline_$Impl_$.explore(_$Pipeline_Pipeline_$Impl_$.open(gui.children),function(x4) {
		return x4.children;
	}),function(x5) {
		if(x5.type != "button") {
			return x5.type == "radio";
		} else {
			return true;
		}
	}),function(x6) {
		return x6.name;
	}),function(x7) {
		console.log(x7);
	});
};
var haxe_IMap = function() { };
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	get: function(key) {
		if(__map_reserved[key] != null) {
			return this.getReserved(key);
		}
		return this.h[key];
	}
	,setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) {
			return null;
		} else {
			return this.rh["$" + key];
		}
	}
	,keys: function() {
		return HxOverrides.iter(this.arrayKeys());
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) {
			out.push(key);
		}
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) {
				out.push(key.substr(1));
			}
			}
		}
		return out;
	}
};
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
var __map_reserved = {}
Sample1.obj = { pxuc : "tjio", pmpt : "leqx", adqa : "pcng", xgzc : "jobm", dlwh : "azel", gqwc : "nvjp", jyih : "cccy", uemc : "wxfa", pfuf : "gnlj", ktxu : "moky"};
Sample1.map = (function($this) {
	var $r;
	var _g = new haxe_ds_StringMap();
	if(__map_reserved["pxuc"] != null) {
		_g.setReserved("pxuc","tjio");
	} else {
		_g.h["pxuc"] = "tjio";
	}
	if(__map_reserved["pmpt"] != null) {
		_g.setReserved("pmpt","leqx");
	} else {
		_g.h["pmpt"] = "leqx";
	}
	if(__map_reserved["adqa"] != null) {
		_g.setReserved("adqa","pcng");
	} else {
		_g.h["adqa"] = "pcng";
	}
	if(__map_reserved["xgzc"] != null) {
		_g.setReserved("xgzc","jobm");
	} else {
		_g.h["xgzc"] = "jobm";
	}
	if(__map_reserved["dlwh"] != null) {
		_g.setReserved("dlwh","azel");
	} else {
		_g.h["dlwh"] = "azel";
	}
	if(__map_reserved["gqwc"] != null) {
		_g.setReserved("gqwc","nvjp");
	} else {
		_g.h["gqwc"] = "nvjp";
	}
	if(__map_reserved["jyih"] != null) {
		_g.setReserved("jyih","cccy");
	} else {
		_g.h["jyih"] = "cccy";
	}
	if(__map_reserved["uemc"] != null) {
		_g.setReserved("uemc","wxfa");
	} else {
		_g.h["uemc"] = "wxfa";
	}
	if(__map_reserved["pfuf"] != null) {
		_g.setReserved("pfuf","gnlj");
	} else {
		_g.h["pfuf"] = "gnlj";
	}
	if(__map_reserved["ktxu"] != null) {
		_g.setReserved("ktxu","moky");
	} else {
		_g.h["ktxu"] = "moky";
	}
	$r = _g;
	return $r;
}(this));
Sample1.main();
})();
