// Generated by Haxe 3.4.0
(function () { "use strict";
var Case10 = function() { };
Case10.main = function() {
	var src = [];
	var pip = src;
	var tar = _$Pipeline_Pipeline_$Impl_$.select(_$Pipeline_Pipeline_$Impl_$.sort(_$Pipeline_Pipeline_$Impl_$.where(pip,function(x) {
		return x.age >= 20;
	}),function(x1,y) {
		if(x1.age > y.age) {
			return 1;
		} else {
			return -1;
		}
	}),function(x2) {
		return x2.name;
	});
	src.push({ name : "nancy", age : 60});
	src.push({ name : "alice", age : 20});
	src.push({ name : "tom", age : 10});
	src.push({ name : "bob", age : 30});
	src.push({ name : "elmo", age : 40});
	var ans = ["alice","bob","elmo","nancy"];
	var itr = $iterator(_$Pipeline_Pipeline_$Impl_$)(tar);
	var _g = 0;
	while(_g < ans.length) {
		var x3 = ans[_g];
		++_g;
		if(!(itr.hasNext() && x3 == itr.next())) {
			console.log("failed");
		}
	}
	if(!(!itr.hasNext())) {
		console.log("failed");
	}
	src.push({ name : "xyz", age : 55});
	ans = ["alice","bob","elmo","xyz","nancy"];
	itr = $iterator(_$Pipeline_Pipeline_$Impl_$)(tar);
	var _g1 = 0;
	while(_g1 < ans.length) {
		var x4 = ans[_g1];
		++_g1;
		if(!(itr.hasNext() && x4 == itr.next())) {
			console.log("failed");
		}
	}
	if(!(!itr.hasNext())) {
		console.log("failed");
	}
};
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var _$Pipeline_Pipeline_$Impl_$ = {};
_$Pipeline_Pipeline_$Impl_$.iterator = function(this1) {
	return $iterator(this1)();
};
_$Pipeline_Pipeline_$Impl_$.where = function(this1,pred) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(pred == null) {
		throw new Error("pred is null");
	}
	return { iterator : function() {
		var fet = false;
		var nex = null;
		var itr = $iterator(this1)();
		var took = true;
		return { hasNext : function() {
			if(!took) {
				return fet;
			}
			took = false;
			while(true) {
				var tmp;
				fet = itr.hasNext();
				if(fet) {
					nex = itr.next();
					tmp = !pred(nex);
				} else {
					tmp = false;
				}
				if(!tmp) {
					break;
				}
			}
			return fet;
		}, next : function() {
			if(!fet) {
				throw new Error("no next");
			}
			took = true;
			return nex;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.select = function(this1,selector) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(selector == null) {
		throw new Error("selector is null");
	}
	return { iterator : function() {
		var fet = false;
		var nex = null;
		var itr = $iterator(this1)();
		var took = true;
		return { hasNext : function() {
			if(!took) {
				return fet;
			}
			took = false;
			fet = itr.hasNext();
			if(!fet) {
				return false;
			}
			var nex1 = itr.next();
			nex = selector(nex1);
			return true;
		}, next : function() {
			if(!fet) {
				throw new Error("no next");
			}
			took = true;
			return nex;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.join = function(this1,tar,join) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(join == null) {
		throw new Error("join is null");
	}
	return { iterator : function() {
		var fet = false;
		var nex = null;
		var elx = null;
		var itrx = $iterator(this1)();
		var itry = null;
		var first = true;
		var took = true;
		return { hasNext : function() {
			if(!took) {
				return fet;
			}
			took = false;
			if(first || !itry.hasNext()) {
				first = false;
				fet = itrx.hasNext();
				if(!fet) {
					return false;
				}
				elx = itrx.next();
				itry = $iterator(_$Pipeline_Pipeline_$Impl_$)(tar);
			}
			fet = itry.hasNext();
			if(!fet) {
				return false;
			}
			var nex1 = itry.next();
			nex = join(elx,nex1);
			return true;
		}, next : function() {
			if(!fet) {
				throw new Error("no next");
			}
			took = true;
			return nex;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.apply = function(this1,com) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(com == null) {
		throw new Error("com is null");
	}
	return { iterator : function() {
		var itr = $iterator(this1)();
		var nex = null;
		var fet = false;
		var took = true;
		return { hasNext : function() {
			if(!took) {
				return fet;
			}
			took = false;
			fet = itr.hasNext();
			if(!fet) {
				return false;
			}
			nex = itr.next();
			com(nex);
			return true;
		}, next : function() {
			if(!fet) {
				throw new Error("no next");
			}
			took = true;
			return nex;
		}};
	}};
};
_$Pipeline_Pipeline_$Impl_$.sort = function(this1,com) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(com == null) {
		throw new Error("com is null");
	}
	return { iterator : function() {
		var ret = [];
		var x = $iterator(this1)();
		while(x.hasNext()) {
			var x1 = x.next();
			ret.push(x1);
		}
		ret.sort(com);
		return HxOverrides.iter(ret);
	}};
};
_$Pipeline_Pipeline_$Impl_$.foreach = function(this1,com) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(com == null) {
		throw new Error("com is null");
	}
	var x = $iterator(this1)();
	while(x.hasNext()) {
		var x1 = x.next();
		com(x1);
	}
};
_$Pipeline_Pipeline_$Impl_$.aggregate = function(this1,zero,agr,saf) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if(agr == null) {
		throw new Error("agr is null");
	}
	var ret = zero;
	var count = 0;
	var x = $iterator(this1)();
	while(x.hasNext()) {
		var x1 = x.next();
		ret = agr(ret,x1);
		++count;
	}
	if(saf != null) {
		return saf(ret,count);
	} else {
		return ret;
	}
};
_$Pipeline_Pipeline_$Impl_$.argmin = function(this1,$eval) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if($eval == null) {
		throw new Error("eval is null");
	}
	var itr = $iterator(this1)();
	if(!itr.hasNext()) {
		throw new Error("no elem");
	}
	var ret = null;
	var val = null;
	while(true) {
		var x = itr.next();
		var y = $eval(x);
		if(val == null || val > y) {
			ret = x;
			val = y;
		}
		if(!itr.hasNext()) {
			break;
		}
	}
	return ret;
};
_$Pipeline_Pipeline_$Impl_$.argmax = function(this1,$eval) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	if($eval == null) {
		throw new Error("eval is null");
	}
	var itr = $iterator(this1)();
	if(!itr.hasNext()) {
		throw new Error("no elem");
	}
	var ret = null;
	var val = null;
	while(true) {
		var x = itr.next();
		var y = $eval(x);
		if(val == null || val < y) {
			ret = x;
			val = y;
		}
		if(!itr.hasNext()) {
			break;
		}
	}
	return ret;
};
_$Pipeline_Pipeline_$Impl_$.first = function(this1) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	var itr = $iterator(this1)();
	if(!itr.hasNext()) {
		throw new Error("no first element");
	}
	return itr.next();
};
_$Pipeline_Pipeline_$Impl_$.last = function(this1) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	var itr = $iterator(this1)();
	if(!itr.hasNext()) {
		throw new Error("no elem");
	}
	var ret;
	while(true) {
		ret = itr.next();
		if(!itr.hasNext()) {
			break;
		}
	}
	return ret;
};
_$Pipeline_Pipeline_$Impl_$.count = function(this1) {
	if(this1 == null) {
		throw new Error("null ref");
	}
	var ret = 0;
	var x = $iterator(this1)();
	while(x.hasNext()) {
		var x1 = x.next();
		++ret;
	}
	return ret;
};
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
Case10.main();
})();
